const words = [
    {"en":"A/B testing","zh":"A/B测试","phon":"eɪ biː ˈtestɪŋ","category":"devops","example":"A/B test two model versions in production","tags":["devops","ai"]},
    {"en":"abort","zh":"中止","phon":"əˈbɔːt","category":"error","example":"Transaction aborted","tags":["error"]},
    {"en":"ACID","zh":"事务特性","phon":"ˈæsɪd","category":"db","example":"transaction guarantees ACID properties","tags":["db"]},
    {"en":"agent","zh":"AI智能体","phon":"ˈeɪdʒənt","category":"ai","example":"build an AI agent that uses multiple tools","tags":["ai"]},
    {"en":"aggregate","zh":"聚合","phon":"ˈæɡrɪɡət","category":"log","example":"aggregate logs by error type and count","tags":["log"]},
    {"en":"AI gateway","zh":"AI网关","phon":"eɪ-aɪ ˈɡetweɪ","category":"devops","example":"deploy AI gateway for model routing and rate limiting","tags":["devops","ai"]},
    {"en":"alerting","zh":"告警","phon":"əˈlɜːtɪŋ","category":"devops","example":"configure alerting rules in Prometheus","tags":["devops"]},
    {"en":"alias","zh":"别名","phon":"ˈeɪliəs","category":"config","example":"alias ll='ls -la' in .bashrc","tags":["config"]},
    {"en":"alignment","zh":"对齐","phon":"əˈlaɪnmənt","category":"ai","example":"RLHF for aligning model with human values","tags":["ai"]},
    {"en":"ansible","zh":"自动化配置工具","phon":"ˈænsɪbəl","category":"devops","example":"ansible-playbook site.yml to provision servers","tags":["devops"]},
    {"en":"Anthropic SDK","zh":"Anthropic开发包","phon":"ænˈθrɒpɪk es-diː-keɪ","category":"dev","example":"pip install anthropic for Claude API","tags":["dev","ai"]},
    {"en":"API key","zh":"API密钥","phon":"eɪ-piː-aɪ kiː","category":"ai","example":"export OPENAI_API_KEY=sk-...","tags":["ai"]},
    {"en":"api_base","zh":"API接口地址","phon":"eɪ-piː-eɪ beɪs","category":"config","example":"set api_base for custom LLM endpoint","tags":["config","ai"]},
    {"en":"archive","zh":"归档文件","phon":"ˈɑːkɪveɪ","category":"git","example":"git archive -o files.tar HEAD","tags":["git"]},
    {"en":"artifact","zh":"构建产物","phon":"ˈɑːtɪfækt","category":"devops","example":"CI artifact: docker image uploaded to registry","tags":["devops"]},
    {"en":"async","zh":"异步","phon":"ˈeɪsɪŋk","category":"dev","example":"async function fetchData()","tags":["dev"]},
    {"en":"asyncio","zh":"异步IO库","phon":"eɪ-es-aɪ-en-es-wai","category":"dev","example":"use asyncio.gather for concurrent LLM calls","tags":["dev"]},
    {"en":"authentication","zh":"身份验证","phon":"ɔːˌθentɪˈkeɪʃən","category":"dev","example":"implement JWT authentication","tags":["dev"]},
    {"en":"authentication error","zh":"认证失败","phon":"ɔːˌθentɪˈkeɪʃən ˈerər","category":"error","example":"Error: incorrect API key authentication failed","tags":["error","ai"]},
    {"en":"authorization","zh":"权限授权","phon":"ˌɔːθəraɪˈzeɪʃən","category":"dev","example":"check authorization before access","tags":["dev"]},
    {"en":"await","zh":"等待","phon":"əˈweɪt","category":"dev","example":"await fetch(url)","tags":["dev"]},
    {"en":"awk","zh":"文本处理","phon":"ɔːk","category":"cli","example":"awk -F: '{print $1}' /etc/passwd","tags":["cli"]},
    {"en":"backoff","zh":"退避重试","phon":"ˈbækɒf","category":"dev","example":"exponential backoff after API rate limit","tags":["dev"]},
    {"en":"backup","zh":"备份","phon":"ˈbækʌp","category":"cli","example":"backup database to S3","tags":["cli"]},
    {"en":"base_url","zh":"服务基础URL","phon":"beɪs yuː-ar-el","category":"config","example":"base_url=https://api.openai.com/v1","tags":["config","ai"]},
    {"en":"batch processing","zh":"批量处理","phon":"bætʃ ˈprəʊsesɪŋ","category":"ai","example":"batch process 1000 prompts via API","tags":["ai"]},
    {"en":"benchmark","zh":"性能基准测试","phon":"ˈbentʃmɑːk","category":"dev","example":"benchmark query performance with EXPLAIN ANALYZE","tags":["dev"]},
    {"en":"bias","zh":"偏差","phon":"ˈbaɪəs","category":"ai","example":"check for demographic bias in model outputs","tags":["ai"]},
    {"en":"bisect","zh":"二分查找定位","phon":"baɪˈsekt","category":"git","example":"git bisect to find the buggy commit","tags":["git"]},
    {"en":"blame","zh":"追溯 blame","phon":"bleɪm","category":"git","example":"git blame file.txt to see who changed lines","tags":["git"]},
    {"en":"blue-green deployment","zh":"蓝绿部署","phon":"bluː-ɡriːn","category":"devops","example":"blue-green deployment reduces downtime","tags":["devops"]},
    {"en":"branch","zh":"分支","phon":"brɑːntʃ","category":"git","example":"create a new branch","tags":["git"]},
    {"en":"build","zh":"构建","phon":"bɪld","category":"devops","example":"build the Docker image","tags":["devops"]},
    {"en":"cache","zh":"缓存","phon":"kæʃ","category":"config","example":"clear the browser cache","tags":["config"]},
    {"en":"callback","zh":"回调","phon":"ˈkɔːlbæk","category":"dev","example":"pass callback function","tags":["dev"]},
    {"en":"canary","zh":"金丝雀发布","phon":"kəˈneəri","category":"devops","example":"canary release: 5% traffic to new version","tags":["devops"]},
    {"en":"cascade","zh":"级联","phon":"kæˈskeɪd","category":"db","example":"ON DELETE CASCADE for foreign key","tags":["db"]},
    {"en":"chain-of-thought","zh":"思维链","phon":"tʃeɪn əv θɔːt","category":"ai","example":"chain-of-thought prompting for reasoning tasks","tags":["ai"]},
    {"en":"charset","zh":"字符集","phon":"ˈtʃɑːsət","category":"config","example":"mysql charset is utf8mb4","tags":["config"]},
    {"en":"chat completion","zh":"对话补全","phon":"tʃæt kəmˈpliːʃən","category":"dev","example":"client.chat.completions.create(messages=[...])","tags":["dev","ai"]},
    {"en":"checkout","zh":"检出/切换","phon":"ˈtʃekaʊt","category":"git","example":"git checkout -b feature","tags":["git"]},
    {"en":"checkpoint","zh":"检查点","phon":"ˈtʃekpɔɪnt","category":"db","example":"checkpoint writes dirty pages to disk","tags":["db"]},
    {"en":"cherry-pick","zh":"摘取提交","phon":"ˈtʃeripɪk","category":"git","example":"cherry-pick commit hash","tags":["git"]},
    {"en":"chmod","zh":"修改权限","phon":"tʃmɒd","category":"cli","example":"chmod +x script.sh to make executable","tags":["cli"]},
    {"en":"chown","zh":"修改所有者","phon":"tʃaʊn","category":"cli","example":"chown -R www-data:www-data /var/www","tags":["cli"]},
    {"en":"circuit breaker","zh":"断路器","phon":"ˈsɜːkɪt ˈbreɪkər","category":"error","example":"circuit breaker open after 5 failures","tags":["error"]},
    {"en":"class","zh":"类","phon":"klɑːs","category":"dev","example":"create a new class","tags":["dev"]},
    {"en":"clone","zh":"克隆仓库","phon":"kləʊn","category":"git","example":"git clone https://github.com/user/repo.git","tags":["git"]},
    {"en":"cluster","zh":"集群","phon":"ˈkʌstər","category":"devops","example":"kubernetes cluster","tags":["devops"]},
    {"en":"commit","zh":"提交","phon":"kəˈmɪt","category":"git","example":"git commit -m 'fix bug'","tags":["git"]},
    {"en":"compile","zh":"编译","phon":"kəmˈpaɪl","category":"dev","example":"compile TypeScript to JS","tags":["dev"]},
    {"en":"completion","zh":"文本补全","phon":"kəmˈpliːʃən","category":"dev","example":"client.completion(model='gpt-4', prompt='...')","tags":["dev","ai"]},
    {"en":"compress","zh":"压缩","phon":"kəmˈpres","category":"cli","example":"zip -r backup.zip data/","tags":["cli"]},
    {"en":"compression","zh":"压缩","phon":"kəmˈpreʃən","category":"config","example":"enable gzip compression in nginx.conf","tags":["config"]},
    {"en":"concurrent","zh":"并发","phon":"kənˈkʌrənt","category":"dev","example":"run 10 concurrent API requests with asyncio","tags":["dev"]},
    {"en":"configmap","zh":"配置映射","phon":"kənˈfiɡmæp","category":"devops","example":"mount configmap as environment variables","tags":["devops"]},
    {"en":"configure","zh":"配置","phon":"kənˈfɪɡər","category":"config","example":"sudo ./configure --prefix=/usr/local","tags":["config"]},
    {"en":"conflict","zh":"冲突","phon":"ˈkɒnflɪkt","category":"error","example":"Port conflict detected","tags":["error"]},
    {"en":"connection pool","zh":"连接池","phon":"kəˈnekʃən puːl","category":"db","example":"configure HikariCP connection pool size","tags":["db"]},
    {"en":"constraint","zh":"约束","phon":"kənˈstreɪnt","category":"db","example":"UNIQUE constraint on email column","tags":["db"]},
    {"en":"container","zh":"容器","phon":"kənˈteɪnər","category":"devops","example":"run in Docker container","tags":["devops"]},
    {"en":"containerize","zh":"容器化","phon":"kənˈteɪnəraɪz","category":"devops","example":"containerize legacy app with Docker","tags":["devops"]},
    {"en":"content filtered","zh":"内容被过滤","phon":"ˈkɒntent ˈfɪltəd","category":"error","example":"Error: content filtered by safety system","tags":["error","ai"]},
    {"en":"context length","zh":"上下文超长","phon":"ˈkɒntekst leŋθ","category":"error","example":"Error: max context length 4096 tokens exceeded","tags":["error","ai"]},
    {"en":"context window","zh":"上下文窗口","phon":"ˈkɒntekst ˈwɪndəʊ","category":"ai","example":"Claude has 200k token context window","tags":["ai"]},
    {"en":"copy","zh":"复制","phon":"ˈkɒpi","category":"cli","example":"cp source dest","tags":["cli"]},
    {"en":"corrupt","zh":"损坏","phon":"kəˈrʌpt","category":"error","example":"Corrupt disk image","tags":["error"]},
    {"en":"cost","zh":"费用","phon":"kɒst","category":"log","example":"log: API cost=$0.03 for this request","tags":["log","ai"]},
    {"en":"crash","zh":"崩溃","phon":"kræʃ","category":"error","example":"Application crashed unexpectedly","tags":["error"]},
    {"en":"CRUD","zh":"增删改查","phon":"siː-ɑːr-yuː-diː","category":"dev","example":"implement CRUD operations for resource","tags":["dev"]},
    {"en":"curl","zh":"HTTP请求","phon":"kɜːl","category":"cli","example":"curl -X POST https://api.example.com","tags":["cli"]},
    {"en":"cursor","zh":"游标","phon":"ˈkɜːsər","category":"db","example":"use cursor to iterate large result set","tags":["db"]},
    {"en":"daemonset","zh":"守护进程集","phon":"ˈdiːmənset","category":"devops","example":"daemonset ensures pod runs on every node","tags":["devops"]},
    {"en":"dataset","zh":"数据集","phon":"ˈdeɪtəset","category":"ai","example":"split dataset into train/val/test sets","tags":["ai"]},
    {"en":"deadlock","zh":"死锁","phon":"ˈdedlɒk","category":"error","example":"database deadlock detected, transaction rolled back","tags":["error"]},
    {"en":"debug","zh":"调试信息","phon":"diːˈbʌɡ","category":"log","example":"[DEBUG] Variable x = 42","tags":["log"]},
    {"en":"decryption","zh":"解密","phon":"diːˈkrɪpʃən","category":"dev","example":"decrypt ciphertext with AES key","tags":["dev"]},
    {"en":"default","zh":"默认值","phon":"dɪˈfɔːlt","category":"config","example":"The default port is 8080","tags":["config"]},
    {"en":"degraded","zh":"降级运行","phon":"dɪˈɡreɪdɪd","category":"error","example":"service degraded due to high load","tags":["error"]},
    {"en":"delete","zh":"删除","phon":"dɪˈliːt","category":"db","example":"DELETE FROM table WHERE id=1","tags":["db"]},
    {"en":"denied","zh":"拒绝访问","phon":"dɪˈnaɪd","category":"error","example":"Permission denied","tags":["error"]},
    {"en":"dependency","zh":"依赖","phon":"dɪˈpendənsi","category":"dev","example":"manage npm dependencies in package.json","tags":["dev"]},
    {"en":"deploy","zh":"部署","phon":"dɪˈplɔɪ","category":"devops","example":"deploy to production","tags":["devops"]},
    {"en":"deserialize","zh":"反序列化","phon":"diːˈsɪəriəlaɪz","category":"dev","example":"deserialize JSON response to model","tags":["dev"]},
    {"en":"df","zh":"磁盘空间","phon":"diː-ef","category":"cli","example":"df -h shows disk space usage","tags":["cli"]},
    {"en":"diff","zh":"差异对比","phon":"dɪf","category":"git","example":"git diff HEAD~1 file.txt","tags":["git"]},
    {"en":"directive","zh":"指令","phon":"dɪˈrektɪv","category":"config","example":"the rewrite directive in nginx.conf","tags":["config"]},
    {"en":"disable","zh":"禁用","phon":"dɪsˈeɪbəl","category":"config","example":"disable the firewall temporarily","tags":["config"]},
    {"en":"du","zh":"目录大小","phon":"diː-yuː","category":"cli","example":"du -sh * shows size of each item","tags":["cli"]},
    {"en":"dump","zh":"转储","phon":"dʌmp","category":"log","example":"core dump generated","tags":["log"]},
    {"en":"embedding","zh":"向量嵌入","phon":"ɪmˈbedɪŋ","category":"ai","example":"use OpenAI embedding for semantic search","tags":["ai"]},
    {"en":"enable","zh":"启用/允许","phon":"ɪˈneɪbəl","category":"config","example":"enable ssl_verify_peer=1 in php.ini","tags":["config"]},
    {"en":"encoding","zh":"编码","phon":"ɪnˈkəʊdɪŋ","category":"config","example":"set encoding=utf-8 in the connection string","tags":["config"]},
    {"en":"encryption","zh":"加密","phon":"ɪnˈkrɪpʃən","category":"dev","example":"enable TLS encryption in transit","tags":["dev"]},
    {"en":"endpoint","zh":"API端点","phon":"ˈendpɔɪnt","category":"dev","example":"POST /api/v1/users endpoint","tags":["dev"]},
    {"en":"entry","zh":"日志条目","phon":"ˈentri","category":"log","example":"Parse each log entry with regex","tags":["log"]},
    {"en":"env","zh":"环境变量","phon":"env","category":"config","example":"set NODE_ENV=production in your env","tags":["config"]},
    {"en":"epoch","zh":"训练轮次","phon":"ˈepɒk","category":"ai","example":"train for 3 epochs over the dataset","tags":["ai"]},
    {"en":"error","zh":"错误","phon":"ˈerər","category":"log","example":"[ERROR] Connection refused","tags":["log"]},
    {"en":"evaluation","zh":"评估","phon":"ɪˌvæljʊˈeɪʃən","category":"ai","example":"run automated evaluation on test set","tags":["ai"]},
    {"en":"exception","zh":"异常","phon":"ɪkˈsepʃən","category":"error","example":"Unhandled exception in main","tags":["error"]},
    {"en":"execute","zh":"执行","phon":"ˈeksɪkjuːt","category":"cli","example":"execute the script","tags":["cli"]},
    {"en":"exhausted","zh":"资源耗尽","phon":"ɪɡˈzɔːstɪd","category":"error","example":"connection pool exhausted","tags":["error"]},
    {"en":"export","zh":"导出","phon":"ɪkˈspɔːt","category":"dev","example":"export default App","tags":["dev"]},
    {"en":"extract","zh":"解压","phon":"ɪkˈstrækt","category":"cli","example":"tar -xzf archive.tar.gz","tags":["cli"]},
    {"en":"facility","zh":"日志设施","phon":"fəˈsɪlɪti","category":"log","example":"syslog facility local0 in rsyslog.conf","tags":["log"]},
    {"en":"failed","zh":"失败","phon":"feɪld","category":"error","example":"Build failed with exit code 1","tags":["error"]},
    {"en":"fallback","zh":"回退/备用","phon":"ˈfɔːlbæk","category":"config","example":"Use 8.8.8.8 as DNS fallback","tags":["config"]},
    {"en":"fatal","zh":"致命错误","phon":"ˈfeɪtəl","category":"log","example":"[FATAL] Out of memory, exiting","tags":["log"]},
    {"en":"feature flag","zh":"功能开关","phon":"ˈfiːtʃər flæɡ","category":"devops","example":"enable feature flag to control rollout","tags":["devops"]},
    {"en":"fetch","zh":"获取","phon":"fetʃ","category":"git","example":"git fetch origin","tags":["git"]},
    {"en":"few-shot","zh":"少样本学习","phon":"fjuː ʃɒt","category":"ai","example":"few-shot learning with 3 examples in prompt","tags":["ai"]},
    {"en":"fine-tune","zh":"微调","phon":"faɪn tuːn","category":"ai","example":"fine-tune GPT-3.5 with company knowledge base","tags":["ai"]},
    {"en":"fine-tuning","zh":"微调","phon":"faɪn ˈtuːnɪŋ","category":"ai","example":"fine-tune Llama2 with custom dataset","tags":["ai"]},
    {"en":"fixture","zh":"测试fixture","phon":"ˈfɪkstʃər","category":"dev","example":"load test fixtures in pytest","tags":["dev"]},
    {"en":"flag","zh":"标志/开关","phon":"flæɡ","category":"config","example":"enable the --verbose flag in the config","tags":["config"]},
    {"en":"flush","zh":"刷新","phon":"flʌʃ","category":"log","example":"flush log buffer to disk","tags":["log"]},
    {"en":"foreign key","zh":"外键","phon":"ˈfɒrən kiː","category":"db","example":"FOREIGN KEY (user_id)","tags":["db"]},
    {"en":"fork","zh":"派生仓库","phon":"fɔːk","category":"git","example":"fork repo on GitHub to your account","tags":["git"]},
    {"en":"framework","zh":"框架","phon":"ˈfreɪmwɜːk","category":"dev","example":"Spring is a popular Java framework","tags":["dev"]},
    {"en":"frequency penalty","zh":"频率惩罚","phon":"ˈfriːkwənsi ˈpenəlti","category":"dev","example":"frequency_penalty=0.5 reduces token repetition","tags":["dev","ai"]},
    {"en":"frozen","zh":"进程冻结","phon":"ˈfrəʊzən","category":"error","example":"application frozen on deadlock","tags":["error"]},
    {"en":"full-text search","zh":"全文搜索","phon":"fʊl tekst sɜːtʃ","category":"db","example":"enable full-text search on article content","tags":["db"]},
    {"en":"function","zh":"函数","phon":"ˈfʌŋkʃən","category":"dev","example":"define a function","tags":["dev"]},
    {"en":"function calling","zh":"函数调用","phon":"ˈfʌŋkʃən ˈkɔːlɪŋ","category":"ai","example":"use function calling to get weather data","tags":["ai"]},
    {"en":"gitignore","zh":"忽略文件配置","phon":"ɡɪtɪɡˈnɔːr","category":"git","example":"add node_modules to .gitignore","tags":["git"]},
    {"en":"GPU","zh":"图形处理器","phon":"dʒiː-piː-yuː","category":"ai","example":"A100 GPU with 80GB VRAM for LLM training","tags":["ai"]},
    {"en":"GPU cluster","zh":"GPU集群","phon":"dʒiː-piː-yuː ˈklʌstər","category":"devops","example":"provision GPU cluster for LLM training","tags":["devops","ai"]},
    {"en":"grafana","zh":"可视化监控面板","phon":"ˈɡrɑːfənə","category":"devops","example":"import dashboard in Grafana for server metrics","tags":["devops"]},
    {"en":"grep","zh":"文本搜索","phon":"ɡrep","category":"cli","example":"grep -r 'error' /var/log","tags":["cli"]},
    {"en":"grounding","zh":"事实 grounding","phon":"ˈɡraʊndɪŋ","category":"ai","example":"web search grounding for factual responses","tags":["ai"]},
    {"en":"hallucination","zh":"AI幻觉/胡说八道","phon":"həˌluːsɪˈneɪʃən","category":"ai","example":"LLMs may produce hallucination on rare facts","tags":["ai"]},
    {"en":"hang","zh":"卡住","phon":"hæŋ","category":"error","example":"Process hang detected","tags":["error"]},
    {"en":"hashing","zh":"哈希计算","phon":"ˈhæʃɪŋ","category":"dev","example":"password hashing with bcrypt","tags":["dev"]},
    {"en":"health check","zh":"健康检查","phon":"helθ tʃek","category":"devops","example":"liveness health check","tags":["devops"]},
    {"en":"helm","zh":"K8s包管理器","phon":"helm","category":"devops","example":"helm install mychart in Kubernetes cluster","tags":["devops"]},
    {"en":"hook","zh":"钩子","phon":"hʊk","category":"dev","example":"useEffect hook in React","tags":["dev"]},
    {"en":"hyperparameter","zh":"超参数","phon":"ˌhaɪpəpəˈræmɪtər","category":"ai","example":"tune hyperparameters like learning rate","tags":["ai"]},
    {"en":"IaC","zh":"基础设施即代码","phon":"aɪ-eɪ-siː","category":"devops","example":"Terraform is a popular IaC tool","tags":["devops"]},
    {"en":"image","zh":"镜像","phon":"ˈɪmɪdʒ","category":"devops","example":"pull nginx image from Docker Hub","tags":["devops"]},
    {"en":"import","zh":"导入","phon":"ɪmˈpɔːt","category":"dev","example":"import React from 'react'","tags":["dev"]},
    {"en":"import error","zh":"导入错误","phon":"ˈɪmpɔːt ˈerər","category":"error","example":"ImportError: No module named 'requests'","tags":["error"]},
    {"en":"incident","zh":"故障/事件","phon":"ˈɪnsɪdənt","category":"devops","example":"declare incident when SLA is breached","tags":["devops"]},
    {"en":"index","zh":"索引","phon":"ˈɪndeks","category":"db","example":"create index on column","tags":["db"]},
    {"en":"inference","zh":"推理/推断","phon":"ˈɪnfərəns","category":"ai","example":"run LLM inference on GPU cluster","tags":["ai"]},
    {"en":"inference endpoint","zh":"推理端点","phon":"ˈɪnfərəns ˈendpɔɪnt","category":"ai","example":"deploy model as serverless inference endpoint","tags":["ai"]},
    {"en":"info","zh":"信息日志","phon":"ˈɪnfəʊ","category":"log","example":"[INFO] Server started on port 3000","tags":["log"]},
    {"en":"ingest","zh":"日志摄取","phon":"ɪnˈdʒest","category":"log","example":"log ingestion pipeline with Filebeat","tags":["log"]},
    {"en":"ingress","zh":"入口","phon":"ˈɪnɡres","category":"devops","example":"configure ingress rules","tags":["devops"]},
    {"en":"inherit","zh":"继承","phon":"ɪnˈherɪt","category":"config","example":"Child theme inherits parent styles","tags":["config"]},
    {"en":"initialize","zh":"初始化","phon":"ɪˈnɪʃəlaɪz","category":"cli","example":"git init","tags":["cli"]},
    {"en":"insert","zh":"插入","phon":"ɪnˈsɜːt","category":"db","example":"INSERT INTO users VALUES()","tags":["db"]},
    {"en":"install","zh":"安装","phon":"ɪnˈstɔːl","category":"cli","example":"npm install express","tags":["cli"]},
    {"en":"interface","zh":"接口","phon":"ˈɪntəfeɪs","category":"dev","example":"define an interface","tags":["dev"]},
    {"en":"interrupted","zh":"中断","phon":"ˌɪntəˈrʌptɪd","category":"error","example":"operation interrupted by user","tags":["error"]},
    {"en":"interval","zh":"间隔","phon":"ˈɪntəvəl","category":"log","example":"health check log interval set to 30s","tags":["log"]},
    {"en":"invalid","zh":"无效的","phon":"ɪnˈvælɪd","category":"error","example":"Invalid argument supplied","tags":["error"]},
    {"en":"invalid request","zh":"无效请求","phon":"ɪnˈvælɪd rɪˈkwest","category":"error","example":"Error: invalid request - missing required field","tags":["error"]},
    {"en":"iterate","zh":"迭代","phon":"ˈɪtəreɪt","category":"dev","example":"iterate over array with forEach","tags":["dev"]},
    {"en":"join","zh":"连接","phon":"dʒɔɪn","category":"db","example":"LEFT JOIN orders ON users.id = orders.user_id","tags":["db"]},
    {"en":"JSON mode","zh":"JSON输出模式","phon":"dʒeɪsən məʊd","category":"ai","example":"enable JSON mode for reliable parsing","tags":["ai"]},
    {"en":"JSON schema","zh":"JSON结构定义","phon":"dʒeɪsən ˈskiːmə","category":"dev","example":"define JSON schema for structured output","tags":["dev","ai"]},
    {"en":"kill","zh":"杀死进程","phon":"kɪl","category":"cli","example":"kill -9 1234","tags":["cli"]},
    {"en":"latency","zh":"延迟","phon":"ˈlætənsi","category":"log","example":"log: LLM inference latency=2.3s","tags":["log","ai"]},
    {"en":"leak","zh":"泄漏","phon":"liːk","category":"error","example":"Memory leak detected","tags":["error"]},
    {"en":"learning rate","zh":"学习率","phon":"ˈlɜːnɪŋ reɪt","category":"ai","example":"set learning rate to 1e-4 for Adam optimizer","tags":["ai"]},
    {"en":"level","zh":"级别","phon":"ˈlevəl","category":"log","example":"Set log level to DEBUG","tags":["log"]},
    {"en":"limit","zh":"限制","phon":"ˈlɪmɪt","category":"config","example":"ulimit -n 65535 to set file descriptor limit","tags":["config"]},
    {"en":"lint","zh":"代码检查","phon":"lɪnt","category":"dev","example":"run ESLint to check code quality","tags":["dev"]},
    {"en":"list","zh":"列出","phon":"lɪst","category":"cli","example":"ls -la","tags":["cli"]},
    {"en":"LLM","zh":"大语言模型","phon":"el-em-el","category":"ai","example":"GPT-4 and Claude are popular LLMs","tags":["ai"]},
    {"en":"lock","zh":"锁","phon":"lɒk","category":"db","example":"row-level lock prevents concurrent update","tags":["db"]},
    {"en":"log","zh":"日志","phon":"lɒɡ","category":"log","example":"Check the access log for details","tags":["log"]},
    {"en":"loop","zh":"死循环","phon":"luːp","category":"error","example":"infinite loop detected in script","tags":["error"]},
    {"en":"loss","zh":"损失函数值","phon":"lɒs","category":"ai","example":"monitor loss convergence during training","tags":["ai"]},
    {"en":"malformed","zh":"格式错误","phon":"mælˈfɔːmd","category":"error","example":"malformed JSON in config file","tags":["error"]},
    {"en":"man","zh":"查看手册","phon":"mæn","category":"cli","example":"man grep shows manual for grep","tags":["cli"]},
    {"en":"max tokens","zh":"最大输出令牌数","phon":"mæks ˈtəʊkənz","category":"ai","example":"set max_tokens=500 to limit response length","tags":["ai"]},
    {"en":"merge","zh":"合并","phon":"mɜːdʒ","category":"git","example":"merge feature branch","tags":["git"]},
    {"en":"message","zh":"对话消息","phon":"ˈmesɪdʒ","category":"dev","example":"messages=[{'role':'user','content':'hi'}]","tags":["dev","ai"]},
    {"en":"method","zh":"方法","phon":"ˈmeθəd","category":"dev","example":"call the method","tags":["dev"]},
    {"en":"middleware","zh":"中间件","phon":"ˈmɪdlweər","category":"dev","example":"add logging middleware to Express","tags":["dev"]},
    {"en":"migrate","zh":"数据迁移","phon":"maɪˈɡreɪt","category":"db","example":"migrate data from MySQL to PostgreSQL","tags":["db"]},
    {"en":"migration","zh":"迁移","phon":"maɪˈɡreɪʃən","category":"db","example":"run database migration","tags":["db"]},
    {"en":"mismatch","zh":"不匹配","phon":"ˈmɪsmætʃ","category":"error","example":"Checksum mismatch","tags":["error"]},
    {"en":"mock","zh":"模拟对象","phon":"mɒk","category":"dev","example":"use mock in unit testing","tags":["dev"]},
    {"en":"mode","zh":"模式","phon":"məʊd","category":"config","example":"run nginx in daemon mode","tags":["config"]},
    {"en":"model","zh":"模型名称","phon":"ˈmɒdəl","category":"config","example":"model=gpt-4o in OpenAI API call","tags":["config","ai"]},
    {"en":"model drift","zh":"模型漂移","phon":"ˈmɒdəl drɪft","category":"devops","example":"monitor model drift in production over time","tags":["devops","ai"]},
    {"en":"model registry","zh":"模型仓库","phon":"ˈmɒdəl ˈredʒɪstri","category":"devops","example":"upload fine-tuned model to model registry","tags":["devops","ai"]},
    {"en":"model serving","zh":"模型服务化","phon":"ˈmɒdəl ˈsɜːvɪŋ","category":"devops","example":"use vLLM for high-throughput model serving","tags":["devops","ai"]},
    {"en":"model unavailable","zh":"模型不可用","phon":"ˈmɒdəl ˌʌnəˈveɪlə